/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cpiuesklcoawoatbcflh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwaXVlc2tsY29hd29hdGJjZmxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwMjM4NzMsImV4cCI6MjA5NDU5OTg3M30.B49V0Maloas-pzxEOEzH-qsKSkA4G9SeDwVE8zJhdH4"
